// Generated by Qure — Flow: "Cart total recalculates after removing an item"

import { test, expect } from '@playwright/test';

test.describe('Cart — total recalculation (Qure)', () => {
  test.beforeEach(async ({ request }) => {
    const response = await request.post('/api/cart/clear');
    expect(response.ok()).toBeTruthy();
  });

  test('cart total updates after removing one of three products', async ({ page }) => {
    const wirelessHeadphonesPrice = 79.99;
    const mechanicalKeyboardPrice = 129.99;
    const usbCHubPrice = 49.99;

    const initialTotal = wirelessHeadphonesPrice + mechanicalKeyboardPrice + usbCHubPrice;
    const totalAfterRemovingUsbCHub = wirelessHeadphonesPrice + mechanicalKeyboardPrice;

    await page.goto('/');

    await page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'Mechanical Keyboard' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'USB-C Hub' }).locator('.add-to-cart').click();

    await page.goto('/cart');

    await expect(page.getByRole('heading', { name: 'Your Cart (3 items)' })).toBeVisible();
    await expect(page.locator('.cart-item')).toHaveCount(3);
    await expect(page.locator('.cart-item').filter({ hasText: 'Wireless Headphones' })).toContainText('Qty: 1 x $79.99');
    await expect(page.locator('.cart-item').filter({ hasText: 'Mechanical Keyboard' })).toContainText('Qty: 1 x $129.99');
    await expect(page.locator('.cart-item').filter({ hasText: 'USB-C Hub' })).toContainText('Qty: 1 x $49.99');
    await expect(page.locator('.cart-total')).toHaveText(`Total: $${initialTotal.toFixed(2)}`);

    const removeUsbCHub = page.locator('.cart-item').filter({ hasText: 'USB-C Hub' }).getByRole('button', { name: /remove/i });
    await expect(removeUsbCHub, 'Cart items should expose a Remove button so totals can update after item removal').toBeVisible({ timeout: 1000 });
    await removeUsbCHub.click();

    await expect(page.getByRole('heading', { name: 'Your Cart (2 items)' })).toBeVisible();
    await expect(page.locator('.cart-item')).toHaveCount(2);
    await expect(page.locator('.cart-item').filter({ hasText: 'USB-C Hub' })).toHaveCount(0);
    await expect(page.locator('.cart-total')).toHaveText(`Total: $${totalAfterRemovingUsbCHub.toFixed(2)}`);
  });
});
