// Generated by Qure — Flow: "Checkout edge cases: exact total, required fields, and cart clearing"

import { test, expect } from '@playwright/test';

test.describe('Checkout — edge cases (Qure)', () => {
  test.beforeEach(async ({ request }) => {
    const response = await request.post('/api/cart/clear');
    expect(response.ok()).toBeTruthy();
  });

  test('two-item checkout total displays dollars and cents', async ({ page }) => {
    await page.goto('/');

    await page.locator('.product-card .add-to-cart').nth(0).click();
    await page.locator('.product-card .add-to-cart').nth(1).click();
    await expect(page.getByText('Browse our catalog. 2 item(s) in cart.')).toBeVisible();

    await page.goto('/cart');
    await expect(page.locator('.cart-item')).toHaveCount(2);
    await expect(page.locator('.cart-total')).toHaveText(/^Total: \$209\.98$/);

    await page.locator('#proceed-to-checkout').click();
    await expect(page).toHaveURL(/\/checkout/);
    await expect(page.locator('.checkout-total')).toHaveText(/^Total: \$209\.98$/);
  });

  test('checkout total never renders invalid fallback values when cart has items', async ({ page }) => {
    await page.goto('/');

    await page.locator('.product-card .add-to-cart').nth(0).click();
    await page.locator('.product-card .add-to-cart').nth(1).click();

    await page.goto('/cart');
    await expect(page.locator('.cart-item')).toHaveCount(2);
    await expect(page.locator('.cart-total')).toHaveText(/^Total: \$209\.98$/);

    await page.locator('#proceed-to-checkout').click();
    await expect(page).toHaveURL(/\/checkout/);
    await expect(page.getByText('2 item(s)')).toBeVisible();

    const checkoutTotal = page.locator('.checkout-total');
    await expect(checkoutTotal).toHaveText(/^Total: \$\d+\.\d{2}$/);
    await expect(checkoutTotal).not.toContainText(/undefined|NaN|\$0\.00/);
    await expect(checkoutTotal).toHaveText(/^Total: \$209\.98$/);
  });

  test('required checkout fields prevent empty order submission', async ({ page }) => {
    await page.goto('/');
    await page.locator('.product-card .add-to-cart').first().click();

    await page.goto('/checkout');
    await expect(page.locator('.checkout-total')).toHaveText('Total: $79.99');

    await page.locator('#checkout-submit').click();

    await expect(page.locator('.order-confirmation')).toHaveCount(0);
    await expect(page.locator('#checkout-name')).toBeVisible();
    await expect(page.locator('#checkout-email')).toBeVisible();
    await expect(page.locator('#checkout-address')).toBeVisible();
  });

  test('successful checkout clears the cart', async ({ page }) => {
    await page.goto('/');
    await page.locator('.product-card .add-to-cart').first().click();

    await page.goto('/checkout');
    await page.locator('#checkout-name').fill('Checkout Customer');
    await page.locator('#checkout-email').fill('checkout@example.com');
    await page.locator('#checkout-address').fill('100 Market St');
    await page.locator('#checkout-submit').click();

    await expect(page.locator('.order-confirmation')).toBeVisible();
    await expect(page.getByText('Your order has been placed')).toBeVisible();

    await page.goto('/cart');
    await expect(page.getByText('Your cart is empty.')).toBeVisible();
    await expect(page.locator('.cart-item')).toHaveCount(0);
  });
});
