// Generated by Qure (JetBrains) — recorded from manual user flow on 2025-01-15
// Flow: "Complete checkout as returning customer"
// Recording: checkout-returning-customer.qure

import { test, expect } from '@playwright/test';

test.describe('Checkout — returning customer (Qure recording)', () => {
  test('logged-in user completes full purchase flow', async ({ page }) => {
    // Navigate to homepage
    await page.goto('/');

    // User clicks on a product
    await page.locator('.product-card').nth(2).click();
    await expect(page.locator('.product-detail')).toBeVisible();

    // Add to cart from product detail page
    await page.locator('.add-to-cart').click();
    await expect(page.locator('.cart-count')).toHaveText('1');

    // Go to cart
    await page.locator('.cart-icon').click();
    await expect(page).toHaveURL(/\/cart/);

    // Verify cart shows the item and a non-zero total
    await expect(page.locator('.cart-item')).toHaveCount(1);
    const cartTotal = page.locator('.cart-total');
    await expect(cartTotal).toBeVisible();
    await expect(cartTotal).not.toHaveText('$0');

    // Proceed to checkout
    await page.locator('#proceed-to-checkout').click();

    // Verify the checkout summary shows a price
    const checkoutTotal = page.locator('.checkout-total');
    await expect(checkoutTotal).toBeVisible();
    await expect(checkoutTotal).not.toBeEmpty();

    // Fill checkout form (user is returning, some fields pre-filled)
    await page.locator('#checkout-name').fill('Returning Customer');
    await page.locator('#checkout-email').fill('returning@example.com');
    await page.locator('#checkout-address').fill('789 Elm St');

    // Submit order
    await page.locator('#checkout-submit').click();

    // Verify confirmation
    await expect(page.locator('.order-confirmation')).toBeVisible();
    await expect(page.getByText('Your order has been placed')).toBeVisible();
  });

  test('checkout summary displays correct total from cart', async ({ page }) => {
    await page.goto('/');

    // Add two different items
    await page.locator('.product-card .add-to-cart').nth(0).click();
    await page.locator('.product-card .add-to-cart').nth(1).click();
    await expect(page.locator('.cart-count')).toHaveText('2');

    // Go to cart, note the total
    await page.goto('/cart');
    const cartTotalText = await page.locator('.cart-total').textContent();

    // Go to checkout, verify the total matches
    await page.locator('#proceed-to-checkout').click();
    const checkoutTotalText = await page.locator('.checkout-total').textContent();

    expect(checkoutTotalText).toBe(cartTotalText);
  });
});
