// Generated by Qure — Flow: "User login/authentication, user profile/settings, and navigation"

import { test, expect } from '@playwright/test';

test.describe('Customer coverage gaps (Qure)', () => {
  test('user login/authentication returns the shopper to the catalog', async ({ page }) => {
    await page.goto('/login');

    await expect(page.getByRole('heading', { name: 'Login' })).toBeVisible();
    await page.locator('#login-email').fill('shopper@example.com');
    await page.locator('#login-password').fill('password123');
    await page.getByRole('button', { name: 'Log in' }).click();

    await expect(page).toHaveURL(/\/$/);
    await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();
  });

  test('user profile/settings redirects unauthenticated shoppers to login', async ({ page }) => {
    await page.goto('/account');

    await expect(page).toHaveURL(/\/login/);
    await expect(page.locator('#login-email')).toBeVisible();
    await expect(page.locator('#login-password')).toBeVisible();
  });

  test('navigation reaches catalog, cart, and login pages', async ({ page }) => {
    await page.goto('/');

    await page.getByRole('link', { name: /Cart/ }).click();
    await expect(page).toHaveURL(/\/cart/);
    await expect(page.getByRole('heading', { name: /Your Cart/ })).toBeVisible();

    await page.getByRole('link', { name: 'ShopApp' }).click();
    await expect(page).toHaveURL(/\/$/);
    await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();

    await page.getByRole('link', { name: 'Login' }).click();
    await expect(page).toHaveURL(/\/login/);
    await expect(page.getByRole('heading', { name: 'Login' })).toBeVisible();
  });
});
