// Generated by Qure — Flow: "Regression guards for cart and checkout total displays"

import { test, expect } from '@playwright/test';

test.describe('Regression guards — cart and checkout totals (Qure)', () => {
  test.beforeEach(async ({ request }) => {
    const response = await request.post('/api/cart/clear');
    expect(response.ok()).toBeTruthy();
  });

  test('homepage stays usable after cart total API changes', async ({ page }) => {
    await page.goto('/');

    await expect(page).toHaveTitle(/ShopApp/);
    await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();
    await expect(page.locator('.product-card')).toHaveCount(4);
    await expect(page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.product-price')).toHaveText('$79.99');

    await page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.add-to-cart').click();
    await expect(page.getByText('Browse our catalog. 1 item(s) in cart.')).toBeVisible();
  });

  test('cart total is the exact sum of line items with currency formatting', async ({ page }) => {
    const wirelessHeadphonesPrice = 79.99;
    const mechanicalKeyboardPrice = 129.99;
    const usbCHubPrice = 49.99;
    const expectedTotal = wirelessHeadphonesPrice * 2 + mechanicalKeyboardPrice + usbCHubPrice;

    await page.goto('/');

    await page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'Mechanical Keyboard' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'USB-C Hub' }).locator('.add-to-cart').click();

    await page.goto('/cart');

    await expect(page.getByRole('heading', { name: 'Your Cart (4 items)' })).toBeVisible();
    await expect(page.locator('.cart-item')).toHaveCount(3);
    await expect(page.locator('.cart-item').filter({ hasText: 'Wireless Headphones' })).toContainText('Qty: 2 x $79.99');
    await expect(page.locator('.cart-item').filter({ hasText: 'Wireless Headphones' })).toContainText('$159.98');
    await expect(page.locator('.cart-item').filter({ hasText: 'Mechanical Keyboard' })).toContainText('Qty: 1 x $129.99');
    await expect(page.locator('.cart-item').filter({ hasText: 'USB-C Hub' })).toContainText('Qty: 1 x $49.99');

    const cartTotal = page.locator('.cart-total');
    await expect(cartTotal).toHaveText(/^Total: \$\d+\.\d{2}$/);
    await expect(cartTotal).not.toContainText(/undefined|NaN|\$0\.00/);
    await expect(cartTotal).toHaveText(`Total: $${expectedTotal.toFixed(2)}`);
  });

  test('checkout total uses the cart total field and remains purchaseable', async ({ page }) => {
    const expectedTotal = 79.99 + 129.99;

    await page.goto('/');

    await page.locator('.product-card').filter({ hasText: 'Wireless Headphones' }).locator('.add-to-cart').click();
    await page.locator('.product-card').filter({ hasText: 'Mechanical Keyboard' }).locator('.add-to-cart').click();

    await page.goto('/cart');
    await expect(page.locator('.cart-total')).toHaveText(`Total: $${expectedTotal.toFixed(2)}`);

    await page.locator('#proceed-to-checkout').click();
    await expect(page).toHaveURL(/\/checkout/);
    await expect(page.getByText('2 item(s)')).toBeVisible();

    const checkoutTotal = page.locator('.checkout-total');
    await expect(checkoutTotal).toHaveText(/^Total: \$\d+\.\d{2}$/);
    await expect(checkoutTotal).not.toContainText(/undefined|NaN|\$0\.00/);
    await expect(checkoutTotal).toHaveText(`Total: $${expectedTotal.toFixed(2)}`);

    await page.locator('#checkout-name').fill('Regression Guard');
    await page.locator('#checkout-email').fill('guard@example.com');
    await page.locator('#checkout-address').fill('123 Guard Ave');
    await page.locator('#checkout-submit').click();

    await expect(page.locator('.order-confirmation')).toBeVisible();
    await expect(page.getByText('Your order has been placed')).toBeVisible();
  });
});
