const fs = require("fs");
const path = require("path");

/**
 * Qure Sync Module
 *
 * Detects, organizes, and extracts rich metadata from Qure-generated tests.
 * Qure tests are Playwright specs generated from the Qure Assistant (JetBrains IDE plugin).
 * They come from either:
 *   - Described scenarios ("Add a test for logging in...")
 *   - Recorded browser flows (click-through recording)
 *
 * This module extracts structured metadata to give the LLM deeper understanding
 * of what user journeys are covered and which pages/selectors are exercised.
 */

// Markers that indicate a test was generated by Qure
const QURE_MARKERS = [
  /generated by qure/i,
  /qure.*recording/i,
  /qure.*flow/i,
  /\.qure$/i,
  /@qure/i,
  /qure-generated/i,
];

/**
 * Detect if a test file was generated by Qure based on comments/metadata.
 */
function isQureGenerated(content) {
  return QURE_MARKERS.some((marker) => marker.test(content));
}

/**
 * Auto-detect Qure tests from any directory — not just the configured qureTestDir.
 * This catches tests that Qure places in non-standard locations.
 */
function autoDetectQureTests(searchDirs = ["tests", "e2e", "test", "__tests__", "spec"]) {
  const detected = [];

  for (const dir of searchDirs) {
    if (!fs.existsSync(dir)) continue;
    walkForQure(dir, detected);
  }

  return detected;
}

function walkForQure(dir, results) {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (["node_modules", ".next", "dist", "build", ".git"].includes(entry.name)) continue;
        walkForQure(full, results);
      } else if (/\.(spec|test)\.(ts|tsx|js|jsx|mjs)$/.test(entry.name)) {
        const content = fs.readFileSync(full, "utf-8");
        if (isQureGenerated(content)) {
          results.push({ filePath: full, content });
        }
      }
    }
  } catch (_) {
    // skip unreadable dirs
  }
}

/**
 * Extract rich metadata from a Qure test file.
 * This gives the LLM structured info about what user journeys are covered.
 */
function extractQureMetadata(testFile) {
  const { content, filePath } = testFile;
  const metadata = {
    filePath,
    flowName: null,
    recording: null,
    generatedDate: null,
    pages: [],
    selectors: [],
    assertions: [],
    userActions: [],
    testNames: [],
  };

  // Extract flow name from comments
  const flowMatch = content.match(/Flow:\s*["']?(.+?)["']?\s*$/m);
  if (flowMatch) metadata.flowName = flowMatch[1].trim();

  // Extract recording source
  const recordingMatch = content.match(/Recording:\s*(.+?)$/m);
  if (recordingMatch) metadata.recording = recordingMatch[1].trim();

  // Extract generation date
  const dateMatch = content.match(/(\d{4}-\d{2}-\d{2})/);
  if (dateMatch) metadata.generatedDate = dateMatch[1];

  // Extract page URLs navigated to
  const gotoMatches = content.matchAll(/page\.goto\(['"](.+?)['"]\)/g);
  for (const m of gotoMatches) {
    if (!metadata.pages.includes(m[1])) metadata.pages.push(m[1]);
  }

  // Extract URL assertions
  const urlMatches = content.matchAll(/toHaveURL\((.+?)\)/g);
  for (const m of urlMatches) {
    metadata.pages.push(m[1].replace(/['"\/]/g, "").trim());
  }

  // Extract selectors used (for understanding which UI elements are exercised)
  const selectorMatches = content.matchAll(/(?:locator|getBy\w+)\(['"](.+?)['"]\)/g);
  for (const m of selectorMatches) {
    if (!metadata.selectors.includes(m[1])) metadata.selectors.push(m[1]);
  }

  // Extract user actions (click, fill, type, press, check, select)
  const actionMatches = content.matchAll(/\.(click|fill|type|press|check|uncheck|selectOption|dblclick|hover)\(/g);
  for (const m of actionMatches) {
    metadata.userActions.push(m[1]);
  }

  // Extract assertions (what the test validates)
  const assertMatches = content.matchAll(/expect\((.+?)\)\.(toBeVisible|toHaveText|toHaveCount|toBeEmpty|not\.toBeEmpty|not\.toHaveText|toContainText|toHaveValue|toBeChecked|toBeEnabled|toBeDisabled)\(/g);
  for (const m of assertMatches) {
    metadata.assertions.push({
      target: m[1].trim().slice(0, 80),
      assertion: m[2],
    });
  }

  // Extract test names
  const testNameMatches = content.matchAll(/test\(['"](.+?)['"]/g);
  for (const m of testNameMatches) {
    metadata.testNames.push(m[1]);
  }

  // Extract describe block name
  const describeMatch = content.match(/describe\(['"](.+?)['"]/);
  if (describeMatch) metadata.flowName = metadata.flowName || describeMatch[1];

  return metadata;
}

/**
 * Analyze coverage gaps — which common user flows are NOT covered by Qure tests.
 * Returns suggestions for what to record next.
 */
function detectCoverageGaps(qureMetadata, changedFiles, depGraph) {
  const suggestions = [];

  // Common critical flows that should be tested
  const criticalFlows = [
    { pattern: /login|auth|sign.?in/i, name: "User login/authentication" },
    { pattern: /register|sign.?up/i, name: "User registration" },
    { pattern: /cart|basket/i, name: "Shopping cart operations" },
    { pattern: /checkout|payment/i, name: "Checkout/payment flow" },
    { pattern: /search/i, name: "Search functionality" },
    { pattern: /profile|account|settings/i, name: "User profile/settings" },
    { pattern: /order|purchase/i, name: "Order management" },
    { pattern: /nav|menu|header/i, name: "Navigation" },
  ];

  // What pages/flows are already covered
  const coveredText = qureMetadata
    .map((m) => [m.flowName, ...m.testNames, ...m.pages, ...m.selectors].join(" "))
    .join(" ");

  // Check which changed files touch uncovered critical flows
  for (const flow of criticalFlows) {
    const isCovered = flow.pattern.test(coveredText);
    const isAffected = changedFiles.some((f) => flow.pattern.test(f));

    if (isAffected && !isCovered) {
      suggestions.push({
        flow: flow.name,
        reason: "Changed files touch this flow but no Qure test covers it",
        priority: "HIGH",
        qureSuggestion: `Record a flow: "${flow.name}" — navigate through the ${flow.name.toLowerCase()} and verify it completes successfully`,
      });
    } else if (!isCovered) {
      suggestions.push({
        flow: flow.name,
        reason: "Common critical flow with no Qure recording",
        priority: "MEDIUM",
        qureSuggestion: `Describe a scenario: "Test ${flow.name.toLowerCase()} end-to-end"`,
      });
    }
  }

  // Check dependency graph for uncovered consumers
  if (depGraph) {
    for (const [changed, importers] of Object.entries(depGraph)) {
      for (const importer of importers) {
        const importerBase = path.basename(importer).toLowerCase();
        const isTested = qureMetadata.some(
          (m) =>
            m.selectors.some((s) => importerBase.includes(s.replace(/[.#\[\]]/g, "").toLowerCase())) ||
            m.pages.some((p) => importerBase.includes(p.replace(/\//g, "").toLowerCase()))
        );

        if (!isTested) {
          suggestions.push({
            flow: `Component: ${path.basename(importer)}`,
            reason: `Imports from changed file \`${changed}\` but is not covered by any Qure test`,
            priority: "HIGH",
            qureSuggestion: `Record a flow that exercises the UI rendered by ${path.basename(importer)}`,
          });
        }
      }
    }
  }

  // Deduplicate
  const seen = new Set();
  return suggestions.filter((s) => {
    const key = s.flow;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * Format Qure metadata into a block for the LLM prompt.
 * This gives the LLM a structured understanding of what Qure covers.
 */
function formatQureMetadataBlock(qureMetadata) {
  if (qureMetadata.length === 0) return "";

  const lines = ["--- BEGIN QURE COVERAGE MAP ---"];

  for (const meta of qureMetadata) {
    lines.push(`\nFlow: ${meta.flowName || path.basename(meta.filePath)}`);
    if (meta.testNames.length > 0) {
      lines.push(`  Tests: ${meta.testNames.join("; ")}`);
    }
    if (meta.pages.length > 0) {
      lines.push(`  Pages visited: ${meta.pages.join(", ")}`);
    }
    if (meta.selectors.length > 0) {
      lines.push(`  UI elements exercised: ${meta.selectors.slice(0, 15).join(", ")}`);
    }
    if (meta.assertions.length > 0) {
      lines.push(`  Assertions: ${meta.assertions.map((a) => a.assertion).join(", ")}`);
    }
    lines.push(`  User actions: ${[...new Set(meta.userActions)].join(", ") || "none detected"}`);
  }

  lines.push("\n--- END QURE COVERAGE MAP ---\n");
  return lines.join("\n");
}

/**
 * Format coverage gap suggestions for the report.
 */
function formatCoverageGaps(suggestions) {
  if (suggestions.length === 0) return "";

  const lines = ["\n### Qure Coverage Suggestions\n"];
  lines.push("The following flows are not covered by Qure recordings and may benefit from it:\n");

  const high = suggestions.filter((s) => s.priority === "HIGH");
  const medium = suggestions.filter((s) => s.priority === "MEDIUM");

  if (high.length > 0) {
    lines.push("**High priority** (affected by this change):");
    for (const s of high) {
      lines.push(`- **${s.flow}** — ${s.reason}`);
      lines.push(`  - Qure action: ${s.qureSuggestion}`);
    }
    lines.push("");
  }

  if (medium.length > 0) {
    lines.push("**Recommended** (common flows to protect):");
    for (const s of medium.slice(0, 5)) {
      lines.push(`- **${s.flow}** — ${s.reason}`);
      lines.push(`  - Qure action: ${s.qureSuggestion}`);
    }
  }

  return lines.join("\n");
}

module.exports = {
  isQureGenerated,
  autoDetectQureTests,
  extractQureMetadata,
  detectCoverageGaps,
  formatQureMetadataBlock,
  formatCoverageGaps,
};
