#!/usr/bin/env node

/**
 * Qure-compatible Vibe Audit runner.
 *
 * This script is designed to be invoked by the Qure AI agent.
 * It runs the Vibe Audit analysis and outputs results in a format
 * that Qure can read and act on (generate missing tests, fix issues).
 *
 * Usage from Qure chat:
 *   "Run node scripts/qure-run.js"
 *   "Run node scripts/qure-run.js --suggest-tests"
 *   "Run node scripts/qure-run.js --check-coverage"
 *
 * Flags:
 *   --suggest-tests    Output specific test scenarios Qure should generate
 *   --check-coverage   Only check which flows lack test coverage
 *   --full             Run the full multi-layer analysis (default)
 *   --json             Output raw JSON instead of markdown
 */

const fs = require("fs");
const path = require("path");
require("dotenv").config();

const { loadConfig } = require("./lib/config");
const { getFilteredDiff } = require("./lib/diff");
const { collectAllTests, formatTestBlock } = require("./lib/tests");
const {
  autoDetectQureTests,
  extractQureMetadata,
  detectCoverageGaps,
} = require("./lib/qure-sync");

const args = process.argv.slice(2);
const MODE = args.includes("--suggest-tests") ? "suggest"
           : args.includes("--check-coverage") ? "coverage"
           : "full";
const JSON_OUTPUT = args.includes("--json");

async function main() {
  const config = loadConfig();

  // ─── Get diff ─────────────────────────────────────────────────────────────────
  let diffResult;
  try {
    diffResult = await getFilteredDiff(config);
  } catch (err) {
    output({ error: `Could not read diff: ${err.message}` });
    return;
  }

  const { diff, files: changedFiles } = diffResult;

  // ─── Collect existing tests ───────────────────────────────────────────────────
  const { handWritten, qureTests } = collectAllTests(config);
  const autoDetected = autoDetectQureTests(config.qure?.scanDirs || []);
  const allQureTests = [...qureTests, ...autoDetected.filter(
    (t) => !qureTests.some((q) => q.filePath === t.filePath)
  )];
  const qureMetadata = allQureTests.map((t) => extractQureMetadata(t));

  // ─── Mode: Coverage Check ─────────────────────────────────────────────────────
  if (MODE === "coverage") {
    const gaps = detectCoverageGaps(qureMetadata, changedFiles, null);
    output({
      mode: "coverage",
      totalTests: handWritten.length + allQureTests.length,
      handWritten: handWritten.length,
      qureGenerated: allQureTests.length,
      qureFlows: qureMetadata.filter((m) => m.flowName).map((m) => ({
        name: m.flowName,
        pages: m.pages,
        assertions: m.assertions.length,
      })),
      gaps: gaps.map((g) => ({
        flow: g.flow,
        priority: g.priority,
        reason: g.reason,
        action: g.qureSuggestion,
      })),
    });
    return;
  }

  // ─── Mode: Suggest Tests ──────────────────────────────────────────────────────
  if (MODE === "suggest") {
    const gaps = detectCoverageGaps(qureMetadata, changedFiles, null);
    const suggestions = [];

    // Suggest based on coverage gaps
    for (const gap of gaps) {
      suggestions.push({
        type: "coverage_gap",
        priority: gap.priority,
        scenario: gap.qureSuggestion,
        reason: gap.reason,
      });
    }

    // Suggest based on changed files that have no test coverage
    for (const file of changedFiles) {
      const hasTest = allQureTests.some((t) =>
        t.content.includes(path.basename(file, path.extname(file)))
      ) || handWritten.some((t) =>
        t.content.includes(path.basename(file, path.extname(file)))
      );

      if (!hasTest && /\.(ts|tsx|js|jsx)$/.test(file) && !file.includes("test") && !file.includes("spec")) {
        const baseName = path.basename(file, path.extname(file));
        suggestions.push({
          type: "untested_file",
          priority: "HIGH",
          scenario: `Record a flow that exercises the UI rendered by ${baseName}. Navigate to the page that uses this component/module and verify it works correctly.`,
          reason: `${file} was changed but no test exercises it`,
          file,
        });
      }
    }

    output({
      mode: "suggest_tests",
      changedFiles,
      suggestions,
      instructions: [
        "BEST: Click Record, navigate the flow in the browser, click Finish, then say 'create a test from this'.",
        "GOOD: Paste the scenario description in the chat and say 'create a test for this'.",
        "Focus on HIGH priority items first — they're affected by the current changes.",
        "Always add '// Generated by Qure' at the top. Save to tests/qure/.",
        "After creating tests, run: node scripts/qure-run.js --check-coverage",
      ],
    });
    return;
  }

  // ─── Mode: Full Analysis ──────────────────────────────────────────────────────
  if (!diff) {
    output({
      mode: "full",
      status: "no_diff",
      message: "No diff found. Create a local-diff.patch or run on a branch with changes.",
    });
    return;
  }

  // Run the full v3 pipeline if available, otherwise fall back to v2
  try {
    // Try v3
    const { runLayer1_Static } = require("./layers/01-static");
    const { runLayer2_TestExecution } = require("./layers/02-test-execution");
    const { runLayer5_Synthesis } = require("./layers/05-synthesis");

    const signals = { diff, changedFiles, truncated: false };
    signals.static = await runLayer1_Static(diff, changedFiles, config);
    signals.testExecution = await runLayer2_TestExecution(changedFiles, config);

    // Skip visual + mutation in Qure context (too heavy for interactive use)
    signals.visual = null;
    signals.mutations = null;

    const analysis = await runLayer5_Synthesis(signals, config);

    if (analysis) {
      output({
        mode: "full",
        status: "complete",
        intent: analysis.intent,
        risks: analysis.risks,
        testGaps: analysis.test_gaps || [],
        coverageGaps: analysis.coverageGaps || [],
        actionItems: generateActionItems(analysis, changedFiles),
      });
    } else {
      output({
        mode: "full",
        status: "synthesis_failed",
        message: "Analysis completed layers 1-2 but AI synthesis failed. Check API key.",
        staticErrors: signals.static?.summary?.errors || 0,
        brokenConsumers: signals.static?.summary?.brokenConsumers || 0,
      });
    }
  } catch (err) {
    output({
      mode: "full",
      status: "error",
      message: err.message,
    });
  }
}

/**
 * Generate actionable items that Qure can directly implement.
 */
function generateActionItems(analysis, changedFiles) {
  const items = [];

  for (const risk of analysis.risks) {
    if (risk.risk_level === "CRITICAL" || risk.risk_level === "HIGH") {
      items.push({
        action: "create_test",
        priority: risk.risk_level,
        description: `Create a test for: ${risk.flow}`,
        scenario: `Record a flow that verifies: ${risk.user_impact || risk.reasoning}. Navigate to ${risk.affected_pages?.[0] || "the affected page"} and assert the correct behavior.`,
      });
    }
  }

  for (const gap of (analysis.test_gaps || [])) {
    items.push({
      action: "create_test",
      priority: "MEDIUM",
      description: gap.description,
      scenario: gap.suggestion,
    });
  }

  return items;
}

function output(data) {
  if (JSON_OUTPUT) {
    console.log(JSON.stringify(data, null, 2));
  } else {
    // Human-readable format that Qure agent can understand
    console.log("\n══════════════════════════════════════════");
    console.log("  VIBE AUDIT RESULTS");
    console.log("══════════════════════════════════════════\n");

    if (data.error) {
      console.log(`ERROR: ${data.error}`);
      return;
    }

    if (data.mode === "coverage") {
      console.log(`Tests: ${data.handWritten} hand-written, ${data.qureGenerated} Qure-generated`);
      console.log(`\nQure-protected flows:`);
      data.qureFlows.forEach((f) => console.log(`  • ${f.name} (${f.pages.join(", ")} — ${f.assertions} assertions)`));
      if (data.gaps.length > 0) {
        console.log(`\nCoverage gaps (${data.gaps.length}):`);
        data.gaps.forEach((g) => {
          console.log(`  [${g.priority}] ${g.flow}`);
          console.log(`    → ${g.action}`);
        });
      } else {
        console.log("\nNo coverage gaps detected.");
      }
    }

    else if (data.mode === "suggest_tests") {
      console.log(`Changed files: ${data.changedFiles.join(", ")}`);
      console.log(`\n${data.suggestions.length} test suggestion(s):\n`);
      data.suggestions.forEach((s, i) => {
        console.log(`${i + 1}. [${s.priority}] ${s.scenario}`);
        console.log(`   Reason: ${s.reason}\n`);
      });
      console.log("\nTo create these tests:");
      data.instructions.forEach((inst) => console.log(`  • ${inst}`));
    }

    else if (data.mode === "full") {
      if (data.status === "no_diff") {
        console.log(data.message);
        return;
      }
      if (data.status === "error") {
        console.log(`Error: ${data.message}`);
        return;
      }

      console.log(`Intent: ${data.intent}`);
      console.log(`\nRisks (${data.risks.length}):`);
      data.risks.forEach((r) => {
        console.log(`  [${r.risk_level}] ${r.flow} (confidence: ${r.confidence}%)`);
        console.log(`    Impact: ${r.user_impact || r.reasoning}`);
        if (r.fix_suggestion) console.log(`    Fix: ${r.fix_suggestion}`);
        console.log();
      });

      if (data.actionItems.length > 0) {
        console.log(`\nAction items for Qure:`);
        data.actionItems.forEach((a) => {
          console.log(`  [${a.priority}] ${a.description}`);
          console.log(`    → ${a.scenario}\n`);
        });
      }
    }
  }
}

main().catch((err) => {
  console.error(`Fatal: ${err.message}`);
  process.exit(1);
});
